import type { Metadata } from "next";
import "./globals.css";
import ProgressProviders from "@/providers/progress-provider";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner";

const inter = localFont({
  src: "./fonts/inter.ttf",
  variable: "--font-inter",
  declarations: [{ prop: "font-feature-settings", value: "'ss01'" }],
});
export const metadata: Metadata = {
  title: "Nevian - Event Management",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export const runtime = "nodejs";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased font-inter`}>
        <ProgressProviders>
          {children}
          <Toaster closeButton richColors position="top-right" />
        </ProgressProviders>
      </body>
    </html>
  );
}
